device.name=Android Device
device.udid=
app.path=
android.app.package=com.saucelabs.mydemoapp.android
android.app.activity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity
android.auto.grant.permissions=true
